httpProxy: "${http_proxy-}"

httpsProxy: "${https_proxy-}"

injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"
npmAuthToken: "${NODE_AUTH_TOKEN-}"
