name: Publish (swc-cli-mux)

on:
    workflow_dispatch:

jobs:
    test:
        name: Publish this package to NPM
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - name: Use Node.js LTS/*
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  registry-url: "https://registry.npmjs.org"
            - run: yarn install
            - run: yarn run build
            - run: yarn workspace swc-cli-mux npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
